### ISSUE TITLE
Problem instaling

### ISSUE THREAD

**Issue by andradecassio** [conre3/pesqEle#3]
I was trying to install the pesqEle package when this error message appeared:

> devtools::install_github("conre3/pesqEle")
 
Downloading GitHub repo conre3/pesqEle@master
from URL https://api.github.com/repos/conre3/pesqEle/zipball/master
Installing pesqEle
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Cássio/AppData/Local/Temp/RtmpoRRhv3/devtools7b1c5aa746d9/conre3-pesqEle-296d610"  \  --library="C:/Users/Cássio/Documents/R/win-library/3.5" --install-tests
 
* installing *source* package 'pesqEle' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/Cassio/Documents/R/win-library/3.5/pesqEle/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") :
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package 'pesqEle'
* removing 'C:/Users/Cássio/Documents/R/win-library/3.5/pesqEle'

In R CMD INSTALL

Installation failed: Command failed (1)

Could anyone help me?

Thanks!!!

**Comment by jtrecenti** [comment]
De acordo com esse issue

https://github.com/r-lib/devtools/issues/1674

pode ser que o problema esteja no fato do seu caminho de instalação ter acentos no nome

veja que 

```
library="C:/Users/Cássio/Documents/R/win-library/3.5"
```

mas o que foi procurado foi

```
 file 'C:/Users/Cassio/Documents/R/win-library/3.5/pesqEle/DESCRIPTION'
```

e Cassio está sem acento no segundo caso.

Sugiro mudar o nome do seu usuário no PC.

**Comment by andradecassio** [comment]
Muito obrigado Júlio!

Problema resolvido.

Atenciosamente,

Cássio Antônio Andrade
